#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Corrige acentuação portuguesa nos scripts do ebook.
Opera SOMENTE dentro de strings Python (aspas simples ou duplas),
nunca em identificadores de código.
"""
import re

# ─── LISTA DE SUBSTITUIÇÕES ──────────────────────────────────────────────────
# Ordem importa: palavras mais específicas/longas primeiro.
REPLACEMENTS = [
    # Erros tipográficos encontrados no script
    ('conscientementre', 'conscientemente'),
    ('indicisos',        'indecisos'),
    ('equilfibrio',      'equilíbrio'),

    # Signos do zodíaco
    ('Aries',        'Áries'),
    ('aries',        'áries'),
    ('ariano',       'ariano'),
    ('arianos',      'arianos'),
    ('ariana',       'ariana'),
    ('arianas',      'arianas'),
    ('Gemeos',       'Gêmeos'),
    ('gemeos',       'gêmeos'),
    ('Cancer',       'Câncer'),
    ('cancer',       'câncer'),
    ('canceriano',   'canceriano'),
    ('canceriana',   'canceriana'),
    ('Leao',         'Leão'),
    ('leao',         'leão'),
    ('leonino',      'leonino'),
    ('Escorpiao',    'Escorpião'),
    ('escorpiao',    'escorpião'),
    ('Sagitario',    'Sagitário'),
    ('sagitario',    'sagitário'),
    ('Capricornio',  'Capricórnio'),
    ('capricornio',  'capricórnio'),
    ('Aquario',      'Aquário'),
    ('aquario',      'aquário'),

    # Planetas
    ('Venus',        'Vênus'),
    ('Mercurio',     'Mercúrio'),
    ('Jupiter',      'Júpiter'),
    ('Plutao',       'Plutão'),
    ('Saturno',      'Saturno'),

    # Termos astronómicos/astrológicos
    ('zodiaco',      'zodíaco'),
    ('Zodiaco',      'Zodíaco'),
    ('triade',       'tríade'),
    ('Triade',       'Tríade'),
    ('astrologico',  'astrológico'),
    ('astrologicos', 'astrológicos'),
    ('astrologica',  'astrológica'),
    ('simbolico',    'simbólico'),
    ('simbolicos',   'simbólicos'),
    ('Simbolico',    'Simbólico'),
    ('simbolo',      'símbolo'),
    ('simbolos',     'símbolos'),
    ('Oraculo',      'Oráculo'),
    ('Babilonios',   'Babilônios'),
    ('babilonios',   'babilônios'),
    ('Arabes',       'Árabes'),
    ('arabes',       'árabes'),

    # Rótulos de seção
    ('PREFACIO',     'PREFÁCIO'),
    ('INDICE',       'ÍNDICE'),
    ('CAPITULO',     'CAPÍTULO'),
    ('Capitulo',     'Capítulo'),
    ('EDICAO',       'EDIÇÃO'),
    ('Edicao',       'Edição'),

    # Palavras comuns sem acento
    ('nao',          'não'),
    ('Nao',          'Não'),
    ('voce',         'você'),
    ('Voce',         'Você'),
    ('tambem',       'também'),
    ('Tambem',       'Também'),
    ('entao',        'então'),
    ('Entao',        'Então'),
    ('porem',        'porém'),
    ('Porem',        'Porém'),
    ('alem',         'além'),
    ('Alem',         'Além'),
    ('Sumario',      'Sumário'),
    ('sumario',      'sumário'),
    ('previa',       'prévia'),
    ('Previa',       'Prévia'),
    ('previsoes',    'previsões'),
    ('previsao',     'previsão'),

    # Verbos e formas verbais específicas
    ('comeca',       'começa'),
    ('comecam',      'começam'),
    ('comecar',      'começar'),
    ('comecou',      'começou'),
    ('comecaram',    'começaram'),
    ('comeco',       'começo'),
    ('comecos',      'começos'),
    ('alcanca',      'alcança'),
    ('alcancam',     'alcançam'),
    ('alcancar',     'alcançar'),
    ('destroi',      'destrói'),
    ('destroca',     'destroça'),

    # Substantivos e adjetivos
    ('Mutavel',      'Mutável'),
    ('mutavel',      'mutável'),
    ('Mutaveis',     'Mutáveis'),
    ('mutaveis',     'mutáveis'),
    ('flexivel',     'flexível'),
    ('flexiveis',    'flexíveis'),
    ('Flexivel',     'Flexível'),
    ('versatil',     'versátil'),
    ('versateis',    'versáteis'),
    ('confiavel',    'confiável'),
    ('confiaveis',   'confiáveis'),
    ('vulneravel',   'vulnerável'),
    ('vulneraveis',  'vulneráveis'),
    ('adaptavel',    'adaptável'),
    ('adaptaveis',   'adaptáveis'),
    ('inabalavel',   'inabalável'),
    ('impossivel',   'impossível'),
    ('Impossivel',   'Impossível'),
    ('possivel',     'possível'),
    ('possiveis',    'possíveis'),
    ('Possivel',     'Possível'),
    ('invisivel',    'invisível'),
    ('visivel',      'visível'),
    ('Visivel',      'Visível'),
    ('sensivel',     'sensível'),
    ('sensiveis',    'sensíveis'),
    ('Sensivel',     'Sensível'),
    ('fragil',       'frágil'),
    ('frageis',      'frágeis'),
    ('estavel',      'estável'),
    ('estaveis',     'estáveis'),
    ('Estavel',      'Estável'),
    ('instavel',     'instável'),
    ('solido',       'sólido'),
    ('solidos',      'sólidos'),
    ('Solido',       'Sólido'),
    ('arquetipo',    'arquétipo'),
    ('arquetipos',   'arquétipos'),
    ('Arquetipo',    'Arquétipo'),
    ('visionario',   'visionário'),
    ('visionarios',  'visionários'),
    ('Visionarios',  'Visionários'),
    ('lider',        'líder'),
    ('lideres',      'líderes'),
    ('Lider',        'Líder'),
    ('Lideres',      'Líderes'),
    ('unico',        'único'),
    ('unica',        'única'),
    ('unicos',       'únicos'),
    ('unicas',       'únicas'),
    ('Unico',        'Único'),
    ('Unica',        'Única'),
    ('rapido',       'rápido'),
    ('rapidos',      'rápidos'),
    ('rapida',       'rápida'),
    ('Rapido',       'Rápido'),
    ('facil',        'fácil'),
    ('faceis',       'fáceis'),
    ('Facil',        'Fácil'),
    ('logico',       'lógico'),
    ('logica',       'lógica'),
    ('Logico',       'Lógico'),
    ('magico',       'mágico'),
    ('magica',       'mágica'),
    ('Magico',       'Mágico'),
    ('romantico',    'romântico'),
    ('romantica',    'romântica'),
    ('Romantico',    'Romântico'),
    ('autentico',    'autêntico'),
    ('Autentico',    'Autêntico'),
    ('energetico',   'energético'),
    ('Energetico',   'Energético'),
    ('analitico',    'analítico'),
    ('analitica',    'analítica'),
    ('Analitico',    'Analítico'),
    ('psicologico',  'psicológico'),
    ('psicologicos', 'psicológicos'),
    ('psicologica',  'psicológica'),
    ('Psicologico',  'Psicológico'),
    ('psiquico',     'psíquico'),
    ('psiquica',     'psíquica'),
    ('psiquicos',    'psíquicos'),
    ('Psiquico',     'Psíquico'),
    ('medianico',    'mediânico'),
    ('magnetico',    'magnético'),
    ('magnetica',    'magnética'),
    ('proprio',      'próprio'),
    ('propria',      'própria'),
    ('proprios',     'próprios'),
    ('proprias',     'próprias'),
    ('Proprio',      'Próprio'),
    ('Propria',      'Própria'),
    ('proximo',      'próximo'),
    ('proxima',      'próxima'),
    ('proximos',     'próximos'),
    ('proximas',     'próximas'),
    ('Proximo',      'Próximo'),
    ('genuino',      'genuíno'),
    ('genuina',      'genuína'),
    ('Genuino',      'Genuíno'),
    ('Genuina',      'Genuína'),
    ('pratico',      'prático'),
    ('praticos',     'práticos'),
    ('pratica',      'prática'),
    ('praticas',     'práticas'),
    ('Pratico',      'Prático'),
    ('Pratica',      'Prática'),
    ('Praticas',     'Práticas'),
    ('ultimo',       'último'),
    ('ultima',       'última'),
    ('ultimos',      'últimos'),
    ('Ultimo',       'Último'),
    ('Ultima',       'Última'),
    ('cronico',      'crônico'),
    ('autonomo',     'autônomo'),
    ('Autonomo',     'Autônomo'),
    ('dinamico',     'dinâmico'),
    ('dinamicos',    'dinâmicos'),
    ('Dinamico',     'Dinâmico'),
    ('sociaveis',    'sociáveis'),
    ('empatico',     'empático'),
    ('empaticos',    'empáticos'),
    ('Empatico',     'Empático'),
    ('egocêntrico',  'egocêntrico'),
    ('egocentrico',  'egocêntrico'),

    # Substantivos abstratos e conceitos
    ('proposito',    'propósito'),
    ('propositos',   'propósitos'),
    ('Proposito',    'Propósito'),
    ('essencia',     'essência'),
    ('Essencia',     'Essência'),
    ('memoria',      'memória'),
    ('Memoria',      'Memória'),
    ('intuicao',     'intuição'),
    ('Intuicao',     'Intuição'),
    ('analise',      'análise'),
    ('Analise',      'Análise'),
    ('analises',     'análises'),
    ('consciencia',  'consciência'),
    ('Consciencia',  'Consciência'),
    ('frequencia',   'frequência'),
    ('Frequencia',   'Frequência'),
    ('independencia','independência'),
    ('Independencia','Independência'),
    ('dependencia',  'dependência'),
    ('Dependencia',  'Dependência'),
    ('principio',    'princípio'),
    ('principios',   'princípios'),
    ('Principio',    'Princípio'),
    ('coincidencia', 'coincidência'),
    ('correspondencia','correspondência'),
    ('ausencia',     'ausência'),
    ('infancia',     'infância'),
    ('Infancia',     'Infância'),
    ('aparencia',    'aparência'),
    ('Aparencia',    'Aparência'),
    ('superficie',   'superfície'),
    ('Superficie',   'Superfície'),
    ('fidelidade',   'fidelidade'),
    ('espiritualidade','espiritualidade'),
    ('espiritual',   'espiritual'),
    ('lealdade',     'lealdade'),
    ('profundidade', 'profundidade'),
    ('Profundidade', 'Profundidade'),
    ('autonomia',    'autonomia'),
    ('reciprocidade','reciprocidade'),
    ('Reciprocidade','Reciprocidade'),
    ('reciproco',    'recíproco'),
    ('reciproca',    'recíproca'),
    ('Reciproco',    'Recíproco'),
    ('paixao',       'paixão'),
    ('Paixao',       'Paixão'),
    ('paixoes',      'paixões'),
    ('vocacao',      'vocação'),
    ('Vocacao',      'Vocação'),
    ('profissao',    'profissão'),
    ('profissoes',   'profissões'),
    ('Profissao',    'Profissão'),
    ('missao',       'missão'),
    ('Missao',       'Missão'),
    ('tradicao',     'tradição'),
    ('tradicoes',    'tradições'),
    ('Tradicao',     'Tradição'),
    ('geracao',      'geração'),
    ('Geracao',      'Geração'),
    ('pertencimento','pertencimento'),
    ('coracao',      'coração'),
    ('coracoes',     'corações'),
    ('Coracao',      'Coração'),
    ('cabeca',       'cabeça'),
    ('Cabeca',       'Cabeça'),
    ('irmao',        'irmão'),
    ('irmaos',       'irmãos'),
    ('habito',       'hábito'),
    ('habitos',      'hábitos'),
    ('Habito',       'Hábito'),
    ('numero',       'número'),
    ('numeros',      'números'),
    ('Numero',       'Número'),
    ('historia',     'história'),
    ('Historia',     'História'),
    ('historico',    'histórico'),
    ('sabedoria',    'sabedoria'),
    ('solidez',      'solidez'),
    ('Solidez',      'Solidez'),
    ('rotulo',       'rótulo'),
    ('Rotulo',       'Rótulo'),
    ('orgulho',      'orgulho'),
    ('verao',        'verão'),
    ('Verao',        'Verão'),
    ('estacao',      'estação'),
    ('estacoes',     'estações'),
    ('carater',      'caráter'),
    ('Carater',      'Caráter'),
    ('periodo',      'período'),
    ('periodos',     'períodos'),
    ('Periodo',      'Período'),
    ('horoscopo',    'horóscopo'),
    ('Horoscopo',    'Horóscopo'),
    ('equilibrio',   'equilíbrio'),
    ('Equilibrio',   'Equilíbrio'),
    ('desequilibrio','desequilíbrio'),
    ('Desequilibrio','Desequilíbrio'),
    ('fisica',       'física'),
    ('fisico',       'físico'),
    ('Fisica',       'Física'),
    ('mascara',      'máscara'),
    ('Mascara',      'Máscara'),
    ('publico',      'público'),
    ('Publico',      'Público'),
    ('critica',      'crítica'),
    ('criticas',     'críticas'),
    ('critico',      'crítico'),
    ('Critica',      'Crítica'),
    ('especifica',   'específica'),
    ('especifico',   'específico'),
    ('especificos',  'específicos'),
    ('Especifica',   'Específica'),
    ('basica',       'básica'),
    ('basico',       'básico'),
    ('Basica',       'Básica'),
    ('generica',     'genérica'),
    ('genericao',    'genérica'),
    ('intima',       'íntima'),
    ('intimos',      'íntimos'),
    ('Intimos',      'Íntimos'),
    ('licenca',      'licença'),
    ('Licenca',      'Licença'),
    ('sentenca',     'sentença'),
    ('crenca',       'crença'),
    ('crenças',      'crenças'),

    # Ações e processos (substantivos)
    ('acao',         'ação'),
    ('Acao',         'Ação'),
    ('acoes',        'ações'),
    ('comunicacao',  'comunicação'),
    ('Comunicacao',  'Comunicação'),
    ('conexao',      'conexão'),
    ('conexoes',     'conexões'),
    ('interacao',    'interação'),
    ('interacoes',   'interações'),
    ('percepcao',    'percepção'),
    ('admiracao',    'admiração'),
    ('admissao',     'admissão'),
    ('permissao',    'permissão'),
    ('permissoes',   'permissões'),
    ('expressao',    'expressão'),
    ('expressoes',   'expressões'),
    ('Expressao',    'Expressão'),
    ('compaixao',    'compaixão'),
    ('Compaixao',    'Compaixão'),
    ('ambicao',      'ambição'),
    ('Ambicao',      'Ambição'),
    ('construcao',   'construção'),
    ('Construcao',   'Construção'),
    ('criacao',      'criação'),
    ('criacoes',     'criações'),
    ('Criacao',      'Criação'),
    ('dissolucao',   'dissolução'),
    ('expansao',     'expansão'),
    ('Expansao',     'Expansão'),
    ('rejeicao',     'rejeição'),
    ('Rejeicao',     'Rejeição'),
    ('reflexao',     'reflexão'),
    ('Reflexao',     'Reflexão'),
    ('reacao',       'reação'),
    ('reacoes',      'reações'),
    ('Reacao',       'Reação'),
    ('Reacoes',      'Reações'),
    ('solucao',      'solução'),
    ('solucoes',     'soluções'),
    ('Solucao',      'Solução'),
    ('conclusao',    'conclusão'),
    ('conclusoes',   'conclusões'),
    ('transformacao','transformação'),
    ('transformacoes','transformações'),
    ('Transformacao','Transformação'),
    ('Transformacoes','Transformações'),
    ('dimensao',     'dimensão'),
    ('Dimensao',     'Dimensão'),
    ('protecao',     'proteção'),
    ('Protecao',     'Proteção'),
    ('determinacao', 'determinação'),
    ('Determinacao', 'Determinação'),
    ('paciencia',    'paciência'),
    ('Paciencia',    'Paciência'),
    ('persistencia', 'persistência'),
    ('resistencia',  'resistência'),
    ('consistencia', 'consistência'),
    ('dependencia',  'dependência'),
    ('tendencia',    'tendência'),
    ('tendencias',   'tendências'),
    ('convicao',     'convicção'),
    ('Convicao',     'Convicção'),
    ('visao',        'visão'),
    ('Visao',        'Visão'),
    ('transicao',    'transição'),
    ('transicoes',   'transições'),
    ('Transicao',    'Transição'),
    ('decisao',      'decisão'),
    ('decisoes',     'decisões'),
    ('relacao',      'relação'),
    ('relacoes',     'relações'),
    ('Relacao',      'Relação'),
    ('posicao',      'posição'),
    ('posicoes',     'posições'),
    ('Posicao',      'Posição'),
    ('emocao',       'emoção'),
    ('emocoes',      'emoções'),
    ('Emocao',       'Emoção'),
    ('Emocoes',      'Emoções'),
    ('sensacao',     'sensação'),
    ('sensacoes',    'sensações'),
    ('Sensacao',     'Sensação'),
    ('situacao',     'situação'),
    ('situacoes',    'situações'),
    ('Situacao',     'Situação'),
    ('interpretacao','interpretação'),
    ('disposicao',   'disposição'),
    ('execucao',     'execução'),
    ('separacao',    'separação'),
    ('Separacao',    'Separação'),
    ('manipulacao',  'manipulação'),
    ('Manipulacao',  'Manipulação'),
    ('satisfacao',   'satisfação'),
    ('Satisfacao',   'Satisfação'),
    ('superacao',    'superação'),
    ('Superacao',    'Superação'),
    ('liberacao',    'liberação'),
    ('Liberacao',    'Liberação'),
    ('destruicao',   'destruição'),
    ('Destruicao',   'Destruição'),
    ('ligacao',      'ligação'),
    ('ligacoes',     'ligações'),
    ('Ligacao',      'Ligação'),
    ('celebracao',   'celebração'),
    ('negociacao',   'negociação'),
    ('preservacao',  'preservação'),
    ('aperfeicoamento','aperfeiçoamento'),
    ('aperfeicoar',  'aperfeiçoar'),
    ('apos',         'após'),
    ('Apos',         'Após'),
    ('seguranca',    'segurança'),
    ('Seguranca',    'Segurança'),
    ('mudanca',      'mudança'),
    ('mudancas',     'mudanças'),
    ('Mudanca',      'Mudança'),
    ('cobranca',     'cobrança'),
    ('licenca',      'licença'),
    ('violencia',    'violência'),
    ('Violencia',    'Violência'),
    ('forca',        'força'),
    ('forcas',       'forças'),
    ('Forca',        'Força'),
    ('Forcas',       'Forças'),
    ('fraca',        'fraca'),
    ('Fraca',        'Fraca'),
    ('alcanca',      'alcança'),
    ('compreensao',  'compreensão'),
    ('Compreensao',  'Compreensão'),
    ('precisao',     'precisão'),
    ('Precisao',     'Precisão'),
    ('inicio',       'início'),
    ('Inicio',       'Início'),
    ('caracteristica','característica'),
    ('caracteristicas','características'),
    ('Caracteristica','Característica'),
    ('vulnerabilidade','vulnerabilidade'),
    ('impulsividade','impulsividade'),
    ('disponibilidade','disponibilidade'),
    ('possessividade','possessividade'),
    ('passividade',  'passividade'),
    ('vitimizacao',  'vitimização'),
    ('traco',        'traço'),
    ('tracos',       'traços'),
    ('Traco',        'Traço'),
    ('Tracos',       'Traços'),
    ('combina',      'combina'),
    ('combinacao',   'combinação'),
    ('combinacoes',  'combinações'),
    ('Combinacao',   'Combinação'),
    ('Combinacoes',  'Combinações'),
    ('atraves',      'através'),
    ('intuitivamente','intuitivamente'),
    ('transcendencia','transcendência'),
    ('renascimento', 'renascimento'),
    ('metamorfose',  'metamorfose'),
    ('metamorfoses', 'metamorfoses'),
    ('magnifico',    'magnífico'),
    ('Magnifico',    'Magnífico'),
    ('abundancia',   'abundância'),
    ('fe\n',         'fé\n'),

    # ÁGUA (especial)
    ('AGUA',         'ÁGUA'),
    ('Agua',         'Água'),
    ('agua',         'água'),

    # Marco → Março
    (' marco ',      ' março '),
    (' Marco ',      ' Março '),
    ('21 de marco',  '21 de março'),

    # Termos específicos do guia
    ('Terminos',     'Términos'),
    ('terminos',     'términos'),
    ('vitimizacao',  'vitimização'),
    ('aprofundar',   'aprofundar'),
    ('revolucao',    'revolução'),
    ('Revolucao',    'Revolução'),
    ('imediatismo',  'imediatismo'),
    ('otimismo',     'otimismo'),
    ('pessimismo',   'pessimismo'),
    ('narcisismo',   'narcisismo'),

    # Acentos em verbos que ficaram sem
    (' e a ',        ' é a '),
    (' e o ',        ' é o '),
    (' e um ',       ' é um '),
    (' e uma ',      ' é uma '),
    (' e seu ',      ' é seu '),
    (' e sua ',      ' é sua '),
    (' e como ',     ' é como '),
    (' e que ',      ' é que '),
    (' e por ',      ' é por '),
    (' e quando ',   ' é quando '),
    (' e onde ',     ' é onde '),
    (' e porque ',   ' é porque '),
    (' e quem ',     ' é quem '),
    (' e isso ',     ' é isso '),
    (' e isso.',     ' é isso.'),
    (' e isso,',     ' é isso,'),
    (' e voce',      ' é você'),
    (' e Voce',      ' é Você'),
    (' E o ',        ' É o '),
    (' E a ',        ' É a '),
    (' E um ',       ' É um '),
    (' E uma ',      ' É uma '),
    (' E isso ',     ' É isso '),
    (' E por ',      ' É por '),
    (' E quando ',   ' É quando '),
    (' E o\n',       ' É o\n'),
    (' E a\n',       ' É a\n'),
    ('"E o ',        '"É o '),
    ('"E a ',        '"É a '),
    ('"E isso',      '"É isso'),
    ('\nE o ',       '\nÉ o '),
    ('\nE a ',       '\nÉ a '),
    ('\nE o\n',      '\nÉ o\n'),
    ('\nE isso',     '\nÉ isso'),
    ('esta ',        'está '),
    ('Esta ',        'Está '),
    ('estao ',       'estão '),
    ('Estao ',       'Estão '),
    ('sao ',         'são '),
    ('Sao ',         'São '),
    (' Ha ',         ' Há '),
    ('\nHa ',        '\nHá '),
    ('"Ha ',         '"Há '),
    ('ha.',          'há.'),
    ('ha,',          'há,'),
    (' ja ',         ' já '),
    (' Ja ',         ' Já '),
    (' ate ',        ' até '),
    (' Ate ',        ' Até '),
    ('ate,',         'até,'),
    ('ate.',         'até.'),
    ('atras',        'atrás'),
    ('Atras',        'Atrás'),
    ('so ',          'só '),
    ('So ',          'Só '),
    ('so.',          'só.'),
    ('so,',          'só,'),
    ('so!',          'só!'),
]


def fix_file(path, replacements):
    """
    Lê o arquivo, aplica correções APENAS dentro de strings Python
    (aspas simples), e salva o resultado.
    """
    with open(path, 'r', encoding='utf-8') as f:
        original = f.read()

    # Usamos um tokenizador simples baseado em regex para encontrar strings.
    # Padrão: string de aspas simples (sem multiline por ora, suficiente aqui)
    STRING_PAT = re.compile(
        r"(?s)"  # DOTALL
        r"('''.*?'''|\"\"\".*?\"\"\"|'(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\")"
    )

    def replace_in_literal(m):
        lit = m.group(0)
        # Mantém as aspas externas; corrige o interior
        if lit.startswith("'''") or lit.startswith('"""'):
            q = lit[:3]
            inner = lit[3:-3]
            return q + apply_replacements(inner, replacements) + q
        else:
            q = lit[0]
            inner = lit[1:-1]
            return q + apply_replacements(inner, replacements) + q

    corrected = STRING_PAT.sub(replace_in_literal, original)

    if corrected != original:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(corrected)
        print(f'[OK] Corrigido: {path}')
    else:
        print(f'[--] Sem alterações: {path}')


def apply_replacements(text, replacements):
    for old, new in replacements:
        text = text.replace(old, new)
    return text


if __name__ == '__main__':
    import os
    base = r'c:\Users\Heitor Melo\Desktop\Grana no Digital\Astrologia'
    scripts = [
        'gerar_ebook_parte1.py',
        'gerar_ebook_parte2.py',
        'gerar_parte3.py',
        'gerar_parte4.py',
        'gerar_bonus.py',
    ]
    for s in scripts:
        path = os.path.join(base, s)
        if os.path.exists(path):
            fix_file(path, REPLACEMENTS)
        else:
            print(f'[AVISO] Não encontrado: {path}')
    print('\nConcluído.')
